name: Docker Image CI

on:
  push:
    paths:
      - "docker_dev/vcpkg_env/Dockerfile"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd docker_dev/vcpkg_env; docker build . --file Dockerfile --tag phantom9999/vcpkg_env:$(date +%s)
